### ISSUE TITLE
Incorrect URL in License

### ISSUE THREAD

**Issue by preloadersnet** [DigitalNZ/supplejack_manager#22]
Hi! 

In the "copyright and licensing" section you have a weird url. When hovered it looks fine, but the problem can be seen if you look in the page source. You will see

http://preloaders.net/en/terms_of_use %E2%80%A8%E2%80%A8

Could you fix it, please. Thanks

**Comment by jamesarobertson** [comment]
Sorry about that, and sorry for the delay in responding. Fixed :-)

http://digitalnz.github.io/supplejack/licence.html
